site_name: Monitoramento de Obras e Serviços Públicos 
repo_name: "MOSP-G8"
repo_url: "https://github.com/unb-mds/MOSP-G8"

theme:
  name: material
  language: "pt"
  features: 
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: green 
      toggle:
        icon: material/brightness-7
        name: alterar para modo dark
      accent: white

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle: 
        icon: material/brightness-4
        name: alterar para modo light

nav: 
  - Início: index.md
  - Atas: 
    - Reunião 30/10: atas/30-10-24.md 
  - Sprint Backlog: 
    - Sprint 1: sprints/sprint1.md
  - Protótipo: prototipo/figma.md
  - Requisitos: requisitos/requisitos.md
  - Roadmap: roadmap/roadmap.md
  - Arquitetura: arquitetura/arquitetura.md