site_name: Monitoramento de Obras e Serviços Públicos 
repo_name: "MOSP-G8"
repo_url: "https://github.com/unb-mds/MOSP-G8"

theme:
  name: material
  language: "pt"
  features: 
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo    
      accent: deep-orange  
      toggle:
        icon: material/brightness-7
        name: alterar para modo dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo    
      accent: deep-orange
      toggle: 
        icon: material/brightness-4
        name: alterar para modo light

nav: 
  - Início: index.md
  - Atas: 
    - Reunião 30/10: atas/30-10-24.md 
    - Reunião 07/11: atas/07-11-24.md
  - Arquitetura do Projeto: arquitetura/arquitetura.md
  - Elicitação dos Requisitos: requisitos/requisitos.md
  - Product Backlog: backlog/backlog.md
  - Protótipo no Figma: prototipo/figma.md
  - Roadmap: roadmap/roadmap.md
  - Sprint Backlog: 
    - Sprint 01: sprints/sprint1.md
    - Sprint 02: sprints/sprint2.md
    - Sprint 03: sprints/sprint3.md
