"""Initial migration

Revision ID: 05ee1254b604
Revises: d47e69473648
Create Date: 2025-02-07 13:01:03.565250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ee1254b604'
down_revision = 'd47e69473648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
