"""Initial migration

Revision ID: 440859a10f81
Revises: af9dd0efd476
Create Date: 2025-02-11 23:26:22.804119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440859a10f81'
down_revision = 'af9dd0efd476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
