"""Add created_at to Obra model

Revision ID: 5203cdbf7593
Revises: 440859a10f81
Create Date: 2025-02-12 00:12:36.321713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5203cdbf7593'
down_revision = '440859a10f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obras', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
