"""Initial migration

Revision ID: 76de26d2f194
Revises: 
Create Date: 2025-01-10 14:54:17.183011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76de26d2f194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('executores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('natureza', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('funcaoSocial', sa.Text(), nullable=False),
    sa.Column('dataInicialPrevista', sa.Date(), nullable=False),
    sa.Column('dataFinalPrevista', sa.Date(), nullable=False),
    sa.Column('fontesDeRecurso', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valorInvestimentoPrevisto', sa.Float(), nullable=False),
    sa.Column('origemRecurso', sa.String(), nullable=False),
    sa.Column('qdtEmpregosGerados', sa.Integer(), nullable=False),
    sa.Column('geometria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    op.drop_table('users')
    op.drop_table('obras')
    # ### end Alembic commands ###
