"""Initial migration

Revision ID: af9dd0efd476
Revises: b14e1d82cd1c
Create Date: 2025-02-11 22:27:17.448920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9dd0efd476'
down_revision = 'b14e1d82cd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
