"""Initial migration

Revision ID: b14e1d82cd1c
Revises: a30db635219d
Create Date: 2025-02-10 00:01:49.895336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14e1d82cd1c'
down_revision = 'a30db635219d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
