"""Initial migration

Revision ID: d47e69473648
Revises: 8817aad36843
Create Date: 2025-02-07 12:57:01.465158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47e69473648'
down_revision = '8817aad36843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
